---
# Will probably need to split this by OS shortly.

# may require ldconfig (possibly via handler)
- name: Add ldconfig entry for new libs (copy file)
  become: true
  # notify: Rebuild ldconfig cache
  ansible.builtin.copy:
    mode: 0644
    src: "files/etc/ld.so.conf.d/mongo.conf"
    dest: "/etc/ld.so.conf.d/"

# note clever naming scheme :D
- name: Render out mongod and systemd config
  become: true
  ansible.builtin.template:
    src: "templates{{ item }}.j2"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - /usr/lib/systemd/system/mongod.service
    - /etc/mongod.conf

- name: Symlink mongod.service into /etc/systemd/...
  become: true
  ansible.builtin.file:
    state: link
    src: "/usr/lib/systemd/system/mongod.service"
    dest: "/etc/systemd/system/multi-user.target.wants/mongod.service"

# handlers are annoying within roles
- name: Rebuild ldconfig cache
  become: true
  ansible.builtin.command: /sbin/ldconfig "{{ mongod_server_path }}/lib" /usr/local/lib

- name: Disable Huge Pages
  become: true
  ignore_errors: true
  ansible.builtin.command: /bin/bash -c 'echo "never" >/sys/kernel/mm/transparent_hugepage/enabled'
