galaxy_info:
  author: Joe OpenSrc
  description:  Percona MongoDB Wrangler

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  # Choose a valid license ID from https://spdx.org - some suggested licenses:
  # - BSD-3-Clause (default)
  # - MIT
  # - GPL-2.0-or-later
  # - GPL-3.0-only
  # - Apache-2.0
  # - CC-BY-4.0
  license: GPL-2.0

  min_ansible_version: 2.10

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  #
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
    - name: SLES
      versions: 
        - 15.3 
        - 15
    - name: opensuse
      versions: 
        - 15.2
        - 15
    - name: Debian
      version: 
        - 9.2
        - stretch

  galaxy_tags: 
    - mongodb
    - percona
    - database 
    - system
     
dependencies: 
  - role: community.general.zypper
  - role: community.general.make

